### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by lukynmatuska** [topi314/Reddit-Discord-Bot#7]
Please add Wiki or `INSTALL.md`.

**Comment by lukynmatuska** [comment]
Invite works fine but I would like to selfhost with awesome project.

**Comment by TopiSenpai** [comment]
it currently does not run well enough to selfhost it
some internal mutex likes to look up every once in a while. I plan on giving selfhost instructions once this is resolved

**Comment by DMTryptamines** [comment]
I would appreciate the documentation as well, this is exactly the bot I'm looking for.

**Comment by TopiSenpai** [comment]
I'm in the process of rewriting it

But I'd be lying if I said I'm actively working on it

**Comment by avasilic** [comment]
Is there any update on this?

**Comment by topi314** [comment]
nope, I've been occupied with other stuff

**Comment by topi314** [comment]
to give you all an update here. See https://github.com/topi314/Reddit-Discord-Bot/pull/9
I think it should be in a functional state now and it now also supports sqlite

That being said, I'm not yet running this is production yet as it needs some more testing & prob some better error handling here & there

**Comment by topi314** [comment]
resolved in https://github.com/topi314/Reddit-Discord-Bot/releases/tag/v2.0.0-beta.1
